djangotweet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('tweetapp.urls')),
    path("", include('django.contrib.auth.urls'))
]

tweetapp/urls.py
from django.urls import path
from . import views

app_name = 'tweetapp'

urlpatterns = [
    path("", views.listtweet, name="listtweet"),
    path("addtweet", views.addtweet, name="addtweet"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
]

tweetapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Tweet(models.Model):
    nickname = models.CharField(max_length=20)
    message = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.nickname}: {self.message}"
    
    class Meta:
        ordering = ['-created_at']

tweetapp/forms.py
from django import forms
from django.contrib.auth.models import User

class CustomUserCreationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "password")

tweetapp/views.py
from django.shortcuts import render, redirect
from . import models
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.views.generic.edit import FormView
from .forms import CustomUserCreationForm
from django.contrib.auth.models import User

def listtweet(request):
    all_tweets = models.Tweet.objects.all().order_by('-created_at')
    tweet_dict = {"tweets" : all_tweets}
    

    return render(request, 'tweetapp/listtweet.html', context=tweet_dict)

@login_required(login_url="/login")
def addtweet(request):
    if request.POST:
        nickname = request.POST["nickname"]
        message = request.POST["message"]
        user = request.user
        models.Tweet.objects.create(nickname=nickname, message=message, user=user)
        return redirect(reverse('tweetapp:listtweet'))
    else:
        return render(request, 'tweetapp/addtweet.html')

class SignUpView(FormView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("tweetapp:listtweet")

    def form_valid(self, form):
        User.objects.create_user(
            username=form.cleaned_data["username"],
            password=form.cleaned_data["password"],
        )
        return super().form_valid(form)

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>neneNe?</title>
</head>
<body style="background-color: #283747;">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 sticky-top">
        <div class="container-fluid">
          <a style="color: #F1F3F4;"  class="navbar-brand" href="{% url 'tweetapp:listtweet' %}">neneNe?</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li style="margin-top: auto; margin-bottom: auto;" class="nav-item">
                <a style="color: #F1F3F4;" class="nav-link active" aria-current="page" href="{% url 'tweetapp:listtweet' %}">paylaşımlar</a>
              </li>
              <li style="margin-top: auto; margin-bottom: auto;" class="nav-item">
                <a style="color: #F1F3F4;"  class="nav-link active" href="{% url 'tweetapp:addtweet' %}">bişeyler saçmala</a>
              </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-md-0">
              <li style="margin-top: auto; margin-bottom: auto;" class="nav-item">
                <a style="color: #F1F3F4;"  class="nav-link active" href="{% url 'login' %}">giriş yap</a>
              </li>
              <li class="nav-item">
                <form style="margin-top: auto; margin-bottom: auto;" action="{% url 'logout' %}?next=/" method="post">             
                  {% csrf_token %}             
                  <button type="submit" style="color: #F1F3F4;"  class="nav-link active btn btn-link">sonrada çıkış yap</button>           
                </form>
              </li>
              <li class="nav-item">
                <a style="color: #F1F3F4;"  class="nav-link active" href="{% url 'tweetapp:signup' %}">ama önce üye ol</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      
    
    {% block content %}



    {% endblock %}

</body>
</html>

tweetapp/templates/tweetapp/addtweet.html
{% extends "base.html" %}


{% block content %}

<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="mb-3" style="margin: 1.5em;">
          <label style="color: #F1F3F4;" for="nickname" class="form-label">adın:</label>
          <input style="background-color: #2C3E50; color: #F1F3F4;" id="nickname" name="nickname" class="form-control" type="text" value={{user.username}} aria-label="readonly input example" readonly>
          <div style="color: #F1F3F4; opacity: 0.5;" id="adın" class="form-text">burayı değiştiremiyon öylesine koydum:)</div>
        </div>
        <div class="mb-3" style="margin: 1.5em;">
          <label style="color: #F1F3F4;" for="message" class="form-label">eee?:</label>
          <textarea style="background-color: #2C3E50; color: #F1F3F4;" type="text" class="form-control" id="message" rows="3" name="message"></textarea>
        </div>
        <button type="submit" class="btn btn-primary" style="margin: 1.5em;">p a y l a ş ş ş ş</button>
      </form>
</div>

{% endblock %}

tweetapp/templates/tweetapp/listtweet.html
{% extends "base.html" %}


{% block content %}
<div class="container">
    
    {% for tweet in tweets %}

        <div class="card shadow-lg" style="padding: 0.5em; margin: 1.5em; background-color: #2C3E50;">

            <div class="card-body">

                <h6 style="color: #F1F3F4;" class="card-title">{{tweet.nickname}} demiş ki:</h6>

                <p style="color: #EAEAEA;" class="card-text">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{tweet.message}}</p>

            </div>

        </div>

    {% endfor %}
    
</div>
{% endblock %}